files:
  - source: /config/**/*.properties
    translation: /%original_path%/%locale_with_underscore%.properties
  - source: /config/**/*.txt
    translation: /%original_path%/%locale_with_underscore%.txt
